# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # optional: [--strict, --force-scope]

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        args: ['--maxkb=10000']
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]

  # Ruff type check
  - repo: local
    hooks:
    -   id: ruff-check
        name: ruff-check
        entry: uv run ruff check
        language: system
        types: [python]

  # Type checking with mypy
  - repo: local
    hooks:
    -   id: mypy
        name: mypy
        # This uses the mypy inside your current uv venv
        entry: uv run mypy src/
        language: system
        types: [python]
        # Mypy often needs to scan the whole project to work correctly
        pass_filenames: false
        stages: [pre-commit]


  # pytest
  - repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: uv run pytest --testmon
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
